import type { AnalyticsRecord, CollectorContext } from "../packages/core/src/types.ts";

export function createMockRecord(id: string): AnalyticsRecord {
  return {
    id,
    timestamp: Date.now(),
    sessionId: "session-1",
    pageUrl: "https://example.com",
    pagePath: "/",
    referrer: "",
    screenWidth: 1920,
    screenHeight: 1080,
    viewportWidth: 1920,
    viewportHeight: 1080,
    devicePixelRatio: 1,
    browser: { name: "Chrome", version: "120.0", engine: "Blink", engineVersion: "120.0", userAgent: "", language: "en-US", cookiesEnabled: true, javaScriptEnabled: true, doNotTrack: null },
    device: { os: "Windows", osVersion: "10/11", platform: "Win32", architecture: "x86_64", formFactor: "desktop", screenWidth: 1920, screenHeight: 1080, viewportWidth: 1920, viewportHeight: 1080, devicePixelRatio: 1, colorDepth: 24, orientation: "landscape-primary", touchSupport: "none", hardwareConcurrency: 8, maxTouchPoints: 0 },
    performance: { navigationTiming: null, paintTiming: null, largestContentfulPaint: null, firstContentfulPaint: null, cumulativeLayoutShift: null, interactionToNextPaint: null, deviceMemory: null, networkType: "unknown", effectiveType: "unknown", downlink: null, rtt: null, saveData: false },
    environment: { timezone: "UTC", timezoneOffset: 0, languages: ["en-US"], language: "en-US", locale: "en-US", prefersColorScheme: "light", prefersReducedMotion: false, prefersContrast: "no-preference", colorGamut: "srgb", hdr: false, localStorageSupport: true, sessionStorageSupport: true, indexedDBSupport: true, cookieSupport: true, cacheAPISupport: true },
    features: { webgl: true, webgl2: true, webgpu: false, wasm: true, webrtc: true, websockets: true, broadcastChannel: true, sharedWorker: false, serviceWorker: true, notifications: true, clipboard: true, fileSystemAccess: false, webShare: true, webAuthn: false, pushManager: true, geolocation: true, bluetooth: false, usb: false, serial: false, gamepad: true, pictureInPicture: true, fullscreen: true },
    interaction: { sessionDuration: 0, timeOnPage: 0, routeChanges: 0, scrollDepth: 0, clickCount: 0, resizeCount: 0, visibilityChanges: 0, focusChanges: 0, landingPage: "https://example.com", exitPage: null, utmSource: null, utmMedium: null, utmCampaign: null, utmTerm: null, utmContent: null },
    metadata: { sdkVersion: "1.0.0", buildTarget: "browser", collectorVersion: "1.0.0", customData: {} },
  };
}

export function createMockContext(overrides?: Partial<CollectorContext>): CollectorContext {
  return {
    document: {
      cookie: "",
      referrer: "",
      title: "Test Page",
      visibilityState: "visible",
      documentElement: { scrollHeight: 1000 },
      createElement: (() => ({ getContext: () => null })) as unknown as Document["createElement"],
      addEventListener: (() => {}) as unknown as Document["addEventListener"],
      removeEventListener: (() => {}) as unknown as Document["removeEventListener"],
    },
    navigator: {
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      language: "en-US",
      languages: ["en-US", "en"],
      platform: "Win32",
      hardwareConcurrency: 8,
      maxTouchPoints: 0,
      cookieEnabled: true,
      doNotTrack: null,
      deviceMemory: undefined,
      connection: undefined,
      storage: undefined,
      clipboard: undefined,
      permissions: undefined,
    },
    window: {
      innerWidth: 1920,
      innerHeight: 1080,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040, colorDepth: 24, pixelDepth: 24, orientation: undefined },
      devicePixelRatio: 1,
      localStorage: undefined,
      sessionStorage: undefined,
      indexedDB: undefined,
      matchMedia: (() => ({ matches: false })) as unknown as Window["matchMedia"],
      addEventListener: (() => {}) as unknown as Window["addEventListener"],
      removeEventListener: (() => {}) as unknown as Window["removeEventListener"],
    },
    performance: {
      timing: undefined,
      navigation: undefined,
      getEntries: (() => []) as unknown as Performance["getEntries"],
      getEntriesByType: (() => []) as unknown as Performance["getEntriesByType"],
      getEntriesByName: (() => []) as unknown as Performance["getEntriesByName"],
      now: (() => 100) as unknown as Performance["now"],
    },
    location: {
      href: "https://example.com",
      origin: "https://example.com",
      pathname: "/",
      search: "",
      hash: "",
      host: "example.com",
      hostname: "example.com",
      protocol: "https:",
      port: "",
    },
    history: {
      length: 1,
      pushState: (() => {}) as unknown as History["pushState"],
      replaceState: (() => {}) as unknown as History["replaceState"],
    },
    screen: {
      width: 1920,
      height: 1080,
      availWidth: 1920,
      availHeight: 1040,
      colorDepth: 24,
      pixelDepth: 24,
      orientation: undefined,
    },
    ...overrides,
  } as unknown as CollectorContext;
}
